### ISSUE TITLE
 Methods defined as TestMethod do not support Web service callouts

### ISSUE THREAD

**Issue by intellectualkid** [bigassforce/aws-sdk#22]
Salesforce throwing following error  " Methods defined as TestMethod do not support Web service callouts"  while i am writing a test class.

Class.AwsSdk.Connector.send: line 210, column 1
Class.AwsSdk.S3.Bucket.listContents: line 76, column 1

**Comment by bigassforce** [comment]
@intellectualkid Thanks for this, will fix.

It looks like the private HttpResponse mocks are not being called by unmanaged test class code, due to salesforce namespace isolation. More info about the phenomenon here: https://salesforce.stackexchange.com/a/18217

In the meantime a workaround is to wrap the method call in `Test.isRunningTest()`

**Comment by intellectualkid** [comment]
Thanks for your quick and kind response. Actually my code is dependent on AwsSdk.S3.Content list

        AwsSdk.S3.Bucket bucket = connector.s3( region ).bucket( bucketName );
        AwsSdk.S3.ListContentsRequest request = new AwsSdk.S3.ListContentsRequest();
        List<AwsSdk.S3.Content> contents = bucket.listContents( request );               

		for (AwsSdk.S3.Content content : contents) { 
                  ...........

           }
if i return fake AwsSdk.S3.Content list, while test is running so i think it would work.

**Comment by intellectualkid** [comment]
@bigassforce i am just Salesforce to integrate with S3.
so if i use S3.cls in my org. would it work for me ?

**Comment by bigassforce** [comment]
Fixed. Yes you can use S3.cls with a Named Credential for the bucket,

**Comment by bigassforce** [comment]
Fixed, please use Named Credential to identify the bucket.
